version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      BOT_TOKEN: "DISCORD_BOT_TOKEN"
      DB_CONNECTION_STRING: "Server=db;Database=DB_DATABASE;User Id=DB_USER;Password=DB_PASSWORD;"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "DB_PASSWORD"
      POSTGRES_USER: "DB_USER"
      POSTGRES_DB: "DB_DATABASE"
  web:
    ports:
      - "8080:80"
    depends_on:
      - db
    image: ghcr.io/jakeygilly/finderweb:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DISCORD_CLIENT_SECRET: "DISCORD_CLIENT_SECRET"
      DISCORD_CLIENT_ID: "DISCORD_CLIENT_ID"
      DISCORD_BOT_TOKEN: "DISCORD_BOT_TOKEN"
      DB_CONNECTION_STRING: "Server=db;Database=DB_DATABASE;User Id=DB_USER;Password=DB_PASSWORD;"
      BOT_OWNERS: "USER_ID,USER_ID"
